import Link from 'next/link';

const services = [
  ['Data Analysis','SPSS, Stata, Excel, EViews, R, Python, Power BI, NVivo and related quantitative or qualitative workflows.'],
  ['Research Assistance','Topic refinement, proposal support, methodology, instruments, results interpretation and academic presentation guidance.'],
  ['Journal & Publication Support','Manuscript preparation, formatting, reference management, journal targeting and reviewer-response support.'],
  ['ICT & Analytics Training','Practical individual and group training in data tools, research methods, dashboards and responsible AI use.'],
  ['Business Analytics','Survey analysis, dashboards, reporting and evidence-based decision support for organisations and SMEs.'],
  ['Consultancy','Custom research, technical documentation, digital strategy, presentations and analytical solutions.']
];

export default function Home(){
  return <main>
    <section className="hero corporate-hero" id="home">
      <div className="container hero-grid">
        <div>
          <span className="eyebrow">Research • Data • Training • Digital Solutions</span>
          <h1>Research. Analyse. Publish. <span>Grow.</span></h1>
          <p>Professional research support, data analysis, academic training and digital solutions for students, researchers, institutions and businesses.</p>
          <div className="hero-actions"><Link className="btn dark" href="/research-hub">Explore Research Hub</Link><Link className="btn" href="/marketplace">Visit Marketplace</Link></div>
          <div className="trust-row"><span>✓ Practical guidance</span><span>✓ Confidential support</span><span>✓ Evidence-led analysis</span></div>
        </div>
        <aside className="hero-card">
          <span className="badge">DATALOG RESEARCH HUB</span>
          <h2>Free tools for better research decisions.</h2>
          <p>Find topics, identify datasets, choose statistical tests, estimate sample sizes and plan your methodology.</p>
          <Link className="text-link" href="/research-hub">Open the Research Hub →</Link>
        </aside>
      </div>
    </section>
    <section className="section" id="services"><div className="container"><div className="section-heading"><span className="eyebrow">What we do</span><h2>Professional support from idea to insight.</h2></div><div className="grid grid3">{services.map(([h,p])=><article className="card service-card" key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="section school-home-feature"><div className="container split"><div><span className="eyebrow light">For school owners and leaders</span><h2>Independent assessment and educational consultancy for better school outcomes.</h2><p>Measure learner performance, verify scheme-of-work and lesson-note coverage, review progress at mid-term and examinations, and receive practical reports for teachers, parents and management.</p><div className="hero-actions"><Link className="btn" href="/schools">Explore school services</Link><Link className="secondary-btn secondary-light" href="/schools#school-consultation">Request consultation</Link></div></div><div className="school-home-points"><span>Curriculum-aligned learner assessment</span><span>Scheme-of-work and lesson-note review</span><span>Cognitive, affective and psychomotor evidence</span><span>Mid-term, termly and end-of-session evaluation</span><span>Teacher feedback and performance analytics</span></div></div></section>
    <section className="section marketplace-preview"><div className="container"><div className="section-heading"><span className="eyebrow light">Datalog Marketplace</span><h2>Buy a useful resource or begin professional work today.</h2><p>Choose affordable templates, premium research tools, structured courses, monthly support or a confidential service order.</p></div><div className="grid grid4"><Link className="market-tile" href="/shop"><strong>Digital Shop</strong><span>Templates and workbooks</span></Link><Link className="market-tile" href="/services/order"><strong>Order a Service</strong><span>Data, research and dashboards</span></Link><Link className="market-tile" href="/courses"><strong>Courses</strong><span>Practical skills and certificates</span></Link><Link className="market-tile" href="/membership"><strong>Membership</strong><span>Recurring tools and support</span></Link></div><Link className="btn" href="/marketplace">Explore the full marketplace</Link></div></section>
    <section className="section alt" id="research"><div className="container split"><div><span className="eyebrow">Datalog Research Hub</span><h2>One research platform inside the Datalog website.</h2><p className="muted">Use free research tools, save work through your account, run a diagnostic, then escalate difficult decisions to a Datalog consultant when needed.</p><Link className="btn dark" href="/research-hub">Explore all research tools</Link></div><div className="grid grid2"><Link className="card" href="/topic-finder"><h3>Project Topic Finder</h3><p>Discover focused, researchable starting points.</p></Link><Link className="card" href="/diagnostic"><h3>Research Diagnostic</h3><p>Check alignment and identify weaknesses early.</p></Link><Link className="card" href="/dashboard"><h3>Research Dashboard</h3><p>Access your saved research workspace.</p></Link><Link className="card" href="/consultation"><h3>Expert Consultation</h3><p>Get professional support for complex work.</p></Link></div></div></section>
    <section className="section" id="training"><div className="container split"><div><span className="eyebrow">Training</span><h2>Learn practical data and research skills.</h2><p className="muted">Training can cover Excel, SPSS, Stata, EViews, R, Python, Power BI, qualitative analysis, research methods and responsible AI for students, researchers and professionals.</p><Link className="btn dark" href="/consultation">Enquire about training</Link></div><div className="card feature-list"><strong>Practical-first</strong><span>Examples, exercises and real research workflows.</span><strong>Flexible delivery</strong><span>Online individual or group training options.</span><strong>Research-to-consultancy</strong><span>Build skills that transfer into academic and professional work.</span></div></div></section>
    <section className="section alt"><div className="container split"><div><span className="eyebrow">Articles & Blog</span><h2>Practical guidance you can apply.</h2><p className="muted">Read clear articles on research design, data analysis, academic reporting, digital tools and evidence-based decision-making.</p><Link className="btn dark" href="/blog">Browse all articles</Link></div><div className="card feature-list"><strong>Research planning</strong><span>Develop focused topics and defensible methods.</span><strong>Data analysis</strong><span>Choose suitable tests and interpret results responsibly.</span><strong>Academic development</strong><span>Improve reporting, presentation and publication readiness.</span></div></div></section>
    <section className="section dark-section" id="about"><div className="container split"><div><span className="eyebrow light">About Datalog ICT</span><h2>Evidence, clarity and practical digital solutions.</h2></div><div><p>Datalog ICT & General Merchandise Ltd is a Nigerian company providing professional data analysis, research support, ICT training and business consultancy services.</p><p>We support students, researchers, academic institutions, professionals and organisations in transforming research questions and raw data into meaningful evidence for decision-making.</p><p><strong>Abeokuta, Ogun State, Nigeria</strong></p></div></div></section>
    <section className="section" id="contact"><div className="container contact-block"><div><span className="eyebrow">Contact</span><h2>Tell us what you are working on.</h2><p className="muted">Research assistance, data analysis, training, consultancy and institutional support.</p></div><div className="contact-actions"><a className="btn dark" href="https://wa.me/2348166414241?text=Hello%20Datalog%20ICT%2C%20I%20would%20like%20to%20discuss%20a%20project." target="_blank" rel="noreferrer">WhatsApp Datalog</a><a className="secondary-btn" href="mailto:milkyades18@gmail.com">milkyades18@gmail.com</a><span>+234 816 641 4241</span></div></div></section>
  </main>
}
