import Link from 'next/link';
import {createSupabaseServerClient} from '@/lib/supabase-server';

export const dynamic='force-dynamic';
export const metadata={title:'My Dashboard | Datalog ICT'};

export default async function DashboardPage(){
  const db=await createSupabaseServerClient();const {data:{user}}=await db?.auth.getUser()||{data:{user:null}};
  if(!db||!user)return <main className="shell narrow"><section className="card auth-card"><h1>Your Datalog workspace</h1><p>Sign in to view purchases, submitted projects, courses, membership and referral rewards.</p><Link className="btn dark" href="/login">Sign in or create account</Link></section></main>;
  const [orders,projects,courses,entitlements,rewards]=await Promise.all([
    db.from('service_orders').select('order_number,project_title,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(5),
    db.from('projects').select('id',{count:'exact',head:true}).eq('user_id',user.id),
    db.from('course_enrollments').select('course_slug,status,progress').eq('user_id',user.id),
    db.from('entitlements').select('item_slug,item_kind,status').eq('user_id',user.id).eq('status','active'),
    db.from('rewards').select('amount_kobo,status').eq('user_id',user.id)
  ]);
  const rewardValue=(rewards.data||[]).filter(x=>x.status!=='declined').reduce((sum,x)=>sum+Number(x.amount_kobo||0),0);
  return <main><section className="dashboard-head"><div className="container"><span className="eyebrow light">My Datalog</span><h1>Welcome back{user.user_metadata?.full_name?`, ${user.user_metadata.full_name}`:''}.</h1><p>Manage your research services, learning and paid access from one workspace.</p></div></section><section className="section"><div className="container"><div className="grid grid4"><div className="card"><h3>Research projects</h3><div className="kpi">{projects.count||0}</div></div><div className="card"><h3>Service requests</h3><div className="kpi">{orders.data?.length||0}</div></div><div className="card"><h3>Courses</h3><div className="kpi">{courses.data?.length||0}</div></div><div className="card"><h3>Referral rewards</h3><div className="kpi">₦{(rewardValue/100).toLocaleString()}</div></div></div><div className="dashboard-grid"><section className="card"><h2>Recent service requests</h2>{orders.data?.length?orders.data.map(order=><div className="dashboard-row" key={order.order_number}><div><strong>{order.project_title}</strong><small>{order.order_number}</small></div><span className="status-pill">{order.status.replace('_',' ')}</span></div>):<div className="empty-state"><p>No professional service request yet.</p><Link className="secondary-btn" href="/services/order">Submit a project</Link></div>}</section><section className="card"><h2>My access</h2>{entitlements.data?.length?entitlements.data.map(item=><div className="dashboard-row" key={item.item_slug}><strong>{item.item_slug.replaceAll('-',' ')}</strong><span className="status-pill">{item.status}</span></div>):<div className="empty-state"><p>No paid resource or membership has been activated.</p><Link className="secondary-btn" href="/marketplace">Explore marketplace</Link></div>}</section><section className="card"><h2>Learning progress</h2>{courses.data?.length?courses.data.map(course=><div key={course.course_slug}><div className="dashboard-row"><strong>{course.course_slug.replaceAll('-',' ')}</strong><span>{course.progress}%</span></div><div className="progress-track"><span style={{width:`${course.progress}%`}}/></div></div>):<div className="empty-state"><p>Your enrolled courses will appear here.</p><Link className="secondary-btn" href="/courses">Browse courses</Link></div>}</section><section className="card quick-actions"><h2>Quick actions</h2><Link href="/diagnostic">Run research diagnostic →</Link><Link href="/topic-finder">Generate topic ideas →</Link><Link href="/referrals">Open referral circle →</Link><Link href="/consultation">Book an expert →</Link></section></div></div></section></main>;
}
